import { createAdminClient } from "@/lib/supabase/server";
import Link from "next/link";

export default async function ScannerPage() {
  const admin = await createAdminClient();
  const { data } = await admin
    .from("agent_runs")
    .select("output, created_at")
    .eq("agent", "scanner")
    .order("created_at", { ascending: false })
    .limit(1)
    .single();

  return (
    <div className="space-y-6 max-w-4xl">
      <div>
        <h1 className="text-2xl font-bold mb-1">🔍 AI Market Scanner</h1>
        <p className="text-[var(--muted)] text-sm">
          Daily picks generated by the Quant Agent across stocks, crypto, and
          commodities. Updated automatically each morning.
        </p>
      </div>

      {!data ? (
        <div className="bg-[var(--card)] border border-[var(--card-border)] rounded-xl p-8 text-center">
          <p className="text-[var(--muted)]">
            No scanner run yet. Cron runs daily at 13 UTC.
          </p>
        </div>
      ) : (
        <>
          <div className="bg-[var(--card)] border border-[var(--card-border)] rounded-xl p-6">
            <div className="flex justify-between items-center mb-4 gap-4 flex-wrap">
              <h2 className="font-semibold">Today&apos;s scan</h2>
              <span className="text-xs text-[var(--muted)]">
                Generated {new Date(data.created_at).toLocaleString()}
              </span>
            </div>
            <div className="prose prose-invert prose-sm max-w-none">
              <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-[var(--foreground)]">
                {data.output}
              </pre>
            </div>
          </div>
          <div className="bg-amber-950 border border-amber-800 rounded-xl p-4 text-amber-200 text-xs">
            ⚠️ Research only. Not financial advice. Verify each idea against
            your own risk tolerance before placing any trade. Risk Agent
            validates every trade you submit.{" "}
            <Link href="/legal" className="underline hover:text-amber-100">
              Full disclaimer
            </Link>
            .
          </div>
        </>
      )}
    </div>
  );
}
