import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Risk Disclaimer & Legal Disclosure",
  description:
    "Financial risk disclaimer for Elexa AI Trading. Research, education, journaling and simulated strategy testing only.",
  robots: { index: true, follow: true },
};

const sections = [
  {
    heading: "Not Financial Advice",
    body: `Elexa AI Trading and its AI agents do not provide investment advice, brokerage services, portfolio management, personal recommendations, regulated financial promotions, or any form of financial advisory service. All platform content, including AI-generated research, trade ideas, analysis, commentary, scanners and strategy outputs, is for education, research, journaling and simulated testing only. Nothing on this platform is a recommendation to buy, sell or hold any security, crypto asset, derivative or financial instrument.`,
  },
  {
    heading: "No Guarantee of Profit",
    body: `There is no guarantee of profit. No trading system, algorithm, AI model, scanner, strategy template or research workflow can guarantee profitable results. Past performance, simulated performance, backtested performance or paper-trading performance does not guarantee or suggest similar future results. You may lose all capital you invest outside this platform.`,
  },
  {
    heading: "Launch Mode: Simulation Only",
    body: `Elexa AI Trading launch mode operates as a research, education, journaling and simulation platform. No real money is moved, no real securities or crypto assets are purchased, and no real trades are executed through launch-mode simulation. Simulated results can differ materially from actual trading results due to liquidity, slippage, fees, spread, latency, taxes, execution quality and market conditions.`,
  },
  {
    heading: "AI Limitations",
    body: `AI-generated outputs are experimental and may be incorrect, incomplete, delayed, biased, outdated or misleading. AI systems cannot account for all market conditions, personal circumstances, tax consequences, regulatory restrictions or suitability factors. AI outputs must not be used as the sole basis for real financial decisions.`,
  },
  {
    heading: "Regulatory Status",
    body: `Elexa AI Trading is not a broker, investment adviser, asset manager, financial planner, exchange, custodian, broker-dealer or regulated trading venue. The platform is not intended to replace licensed professional advice. Users are responsible for checking the laws, regulations and financial-promotion rules that apply in their jurisdiction.`,
  },
  {
    heading: "Risk of Loss",
    body: `Trading securities, options, futures, forex, cryptocurrencies and other financial instruments carries a high level of risk and may not be suitable for all investors. Digital assets can be extremely volatile. Before making any real investment decision outside this platform, carefully consider your objectives, experience, financial position and risk appetite.`,
  },
  {
    heading: "Third-Party Services",
    body: `This platform may integrate with third-party services such as data providers, AI providers, authentication providers, payment processors and broker or exchange sandboxes. Elexa AI Trading is not responsible for the accuracy, availability, security or reliability of third-party services. Use of third-party services is subject to their own terms, privacy policies and risk disclosures.`,
  },
  {
    heading: "Consult a Professional",
    body: `Before making any real investment, tax or trading decision, consult a licensed and regulated professional who understands your circumstances and jurisdiction. Do not make real financial decisions based only on content generated by this platform.`,
  },
];

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16">
      <div className="inline-block bg-amber-950 border border-amber-800 text-amber-300 text-xs font-semibold px-3 py-1 rounded-full mb-6">
        Legal Disclosure — Read Carefully
      </div>
      <h1 className="text-4xl font-bold mb-4">Risk Disclaimer</h1>
      <p className="text-[var(--muted)] mb-10 text-lg">
        By accessing or using Elexa AI Trading, you acknowledge that you have
        read, understood, and agree to the following disclosures.
      </p>

      <div className="space-y-8">
        {sections.map((s) => (
          <div
            key={s.heading}
            className="border-l-2 border-indigo-700 pl-6"
          >
            <h2 className="text-lg font-semibold mb-2">{s.heading}</h2>
            <p className="text-[var(--muted)] leading-relaxed text-sm">
              {s.body}
            </p>
          </div>
        ))}
      </div>

      <div className="mt-12 p-6 bg-amber-950 border border-amber-800 rounded-xl">
        <p className="text-amber-300 font-semibold mb-2">
          Summary — Plain English
        </p>
        <ul className="text-amber-200 text-sm space-y-1 list-disc list-inside">
          <li>This is a research, education, journaling and simulation tool.</li>
          <li>It is not financial advice or a personal recommendation service.</li>
          <li>Profits are not guaranteed. Real investing can lose money.</li>
          <li>Launch-mode trading is simulated. No real money moves.</li>
          <li>AI outputs can be wrong. Do not rely on them alone.</li>
          <li>Talk to a licensed professional before investing.</li>
        </ul>
      </div>

      <p className="mt-8 text-xs text-[var(--muted)]">
        Last updated: July 2026
      </p>
    </div>
  );
}
