import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Risk Disclaimer & Legal Disclosure",
  description:
    "Full financial risk disclaimer for Elexa AI Trading. Read before using the platform.",
  robots: { index: true, follow: true },
};

const sections = [
  {
    heading: "Not Financial Advice",
    body: `Elexa AI Trading and its AI agents do not provide investment advice, brokerage services, portfolio management, or any form of financial advisory services. All content on this platform — including AI-generated signals, trade ideas, analysis, and commentary — is for educational and research purposes only. Nothing on this platform constitutes a recommendation to buy or sell any security.`,
  },
  {
    heading: "No Guarantee of Profit",
    body: `There is no guarantee of profit. No trading system, algorithm, or AI model can guarantee profitable results. Past performance of any strategy, agent, or signal presented on this platform does not guarantee or even suggest similar future results. You may lose all capital you invest.`,
  },
  {
    heading: "Paper Trading Environment",
    body: `Elexa AI Trading operates exclusively in a simulated (paper trading) environment using Alpaca Markets' paper trading API. No real money is moved, no real securities are purchased, and no real trades are executed through this platform. Simulated results may differ materially from actual trading results due to market liquidity, slippage, fees, and other factors not reflected in simulation.`,
  },
  {
    heading: "AI Agent Limitations",
    body: `AI-generated content, signals, and decisions produced by the Elexa agent system are experimental. AI models can produce incorrect, outdated, or misleading outputs. They do not have access to real-time complete market data, cannot account for all market conditions, and should never be used as the sole basis for real financial decisions.`,
  },
  {
    heading: "Regulatory Status",
    body: `Elexa AI Trading LLC is not registered with the U.S. Securities and Exchange Commission (SEC), the Financial Industry Regulatory Authority (FINRA), the Commodity Futures Trading Commission (CFTC), or any other financial regulatory body. This platform does not constitute a brokerage service, investment advisor, or broker-dealer.`,
  },
  {
    heading: "Risk of Loss",
    body: `Trading securities, options, futures, forex, cryptocurrencies, and other financial instruments carries a high level of risk and may not be suitable for all investors. The high degree of leverage that is often obtainable can work against you as well as for you. Before deciding to invest, you should carefully consider your investment objectives, level of experience, and risk appetite.`,
  },
  {
    heading: "Third-Party Services",
    body: `This platform integrates with third-party services including Alpaca Markets and Anthropic. Elexa AI Trading is not responsible for the accuracy, availability, or reliability of these services. Use of third-party services is subject to their respective terms of service and risk disclosures.`,
  },
  {
    heading: "Consult a Professional",
    body: `Before making any real investment or trading decisions, consult a licensed and regulated financial advisor, broker-dealer, or investment advisor registered with the appropriate regulatory authority in your jurisdiction. Do not make financial decisions based on content generated by this platform.`,
  },
];

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16">
      <div className="inline-block bg-amber-950 border border-amber-800 text-amber-300 text-xs font-semibold px-3 py-1 rounded-full mb-6">
        Legal Disclosure — Read Carefully
      </div>
      <h1 className="text-4xl font-bold mb-4">Risk Disclaimer</h1>
      <p className="text-[var(--muted)] mb-10 text-lg">
        By accessing or using Elexa AI Trading, you acknowledge that you have
        read, understood, and agree to the following disclosures.
      </p>

      <div className="space-y-8">
        {sections.map((s) => (
          <div
            key={s.heading}
            className="border-l-2 border-indigo-700 pl-6"
          >
            <h2 className="text-lg font-semibold mb-2">{s.heading}</h2>
            <p className="text-[var(--muted)] leading-relaxed text-sm">
              {s.body}
            </p>
          </div>
        ))}
      </div>

      <div className="mt-12 p-6 bg-amber-950 border border-amber-800 rounded-xl">
        <p className="text-amber-300 font-semibold mb-2">
          Summary — Plain English
        </p>
        <ul className="text-amber-200 text-sm space-y-1 list-disc list-inside">
          <li>This is a research tool. Not financial advice.</li>
          <li>Profits are not guaranteed. You can lose everything.</li>
          <li>All trades are simulated. No real money moves.</li>
          <li>AI signals are experimental. Do not rely on them for real decisions.</li>
          <li>We are not registered financial advisors or brokers.</li>
          <li>Talk to a licensed financial advisor before investing.</li>
        </ul>
      </div>

      <p className="mt-8 text-xs text-[var(--muted)]">
        Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
      </p>
    </div>
  );
}
